image:
  - Visual Studio 2013

platform:
  - x64

environment:
  global:
    GAMEKIT_SYSTEM_NAME: post-man
    GAMEKIT_APPLICATION_PACKAGE: post-man
    GAMEKIT_APPLICATION_MAIN_CLASS: post-man
    GAMEKIT_ARTIFACT: $(GAMEKIT_SYSTEM_NAME)-x86-64-windows-$(APPVEYOR_REPO_TAG_NAME).zip
    GAMEKIT_BUILD_DIR: $(TMP)\$(GAMEKIT_SYSTEM_NAME)

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - set PATH=C:\msys64\usr\bin\;%PATH%
  - pacman --noconfirm -Syu
  - pacman --noconfirm -S zip mingw-w64-x86_64-git-lfs
  - git lfs install
  - git lfs pull
  - curl -L http://bodge.borodust.org/files/install.sh | sh -s ccl
  - sh -c "$HOME/.bodge/bin/lisp install-testing-dist"


build_script:
  - >
    sh -c "$HOME/.bodge/bin/lisp build-gamekit-system
    %GAMEKIT_SYSTEM_NAME% %GAMEKIT_APPLICATION_PACKAGE% %GAMEKIT_APPLICATION_MAIN_CLASS%
    $(cygpath -m '%APPVEYOR_BUILD_FOLDER%')
    $(cygpath -m '%GAMEKIT_BUILD_DIR%')"
  - mv %GAMEKIT_BUILD_DIR%\%GAMEKIT_SYSTEM_NAME%.zip %GAMEKIT_ARTIFACT%

artifacts:
  - path: "%GAMEKIT_ARTIFACT%"
    name: release_archive

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: release_archive
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
