language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: post-statics
  - GAMEKIT_APPLICATION_PACKAGE: post-statics
  - GAMEKIT_APPLICATION_MAIN_CLASS: post-statics
  - PATH: ~/.bodge/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
  - secure: "kFHYnZN0WK3jd5Am+dimOLoaQ3TnUC/bbQC8s1sH5gvB/N09XtfJHyUS8zNhfxBdWSCjQqSBrXqJiRnGIIA46TWjqYMfxkCYTiWgCMpxuWZnaW3EDMUvYrXnzXKhREQH9bFNOdQXGyz3JHwGXovxwfjG9/SaSIIKSTNv9F3TK2faKd/SXd8xUGvCc+Sx2LaFOx3Q7ETAaCujDpmmycfqZ6/8dhWikVpT8e2gN57cSBbKiIBObJMDbLqhaCjcY8VwsTjmSHD5p+LpzJXhXvrQdbdDiyPsndu4tzJ5Afzzk596utQS7Jhv7dF4GIa6zSjKeYVDcHQY1hkGDFXbE8Y0x2lEzpTqGJvzVn8dOFG67NIw4IG8uvNNpPuMBs+1WuAGL7219eQQpnBbWvbHnduNT41izoYFtBTLCOL2OEd2punSFZyrGr6LAZyasSTs/+NnVlx/qPMnTDRJJTep8TVvj/wo51JkRTGbHaYPMRnUU6oi+UrHGjbinSJP3rUkI645mAfp31ab4mEPFZJRQuWZ6JyFpLTUjd5SVrID6Zni35x6lw5+UK/9YW+mM99b0EM3T+UNUNdEYMKTB4XzAXCgcuuz/O+6uWOtX86jsLN4DJPa5FvLQuA1ymOSt26HD2c+P9ICJCvny6jFuOhqflZp5K3c8+/fQ6Rtu0O+ivPj+ok="

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - git lfs install && git lfs pull
  - lisp install-testing-dist

script:
  - >
    lisp build-gamekit-system
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
